name: Github Trend Daily

on:
  schedule:
    # - cron: "0 0 * * *" # Run every day at midnight UTC
    - cron: "0 15 * * *"
  workflow_dispatch: {}

jobs:
  generate-and-upload:
    name: Generate and upload trend data to kaggle
    runs-on: ubuntu-latest
    env:
      DATE_RANGE: daily

    steps:
      - name: 0. Print current date and time
        run: echo "The current date and time is $(date)"

      - name: 1. ğŸ“Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: 2. ğŸ“¦Install ghtrend package and Kaggle cli
        run: pip install ghtrend kaggle

      - name: 3. ğŸ”‘Authenticate with Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ vars.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_API_TOKEN }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: 4. ğŸ“¥Download dataset and uncompress it
        run: |
          kaggle datasets download ${{ vars.KAGGLE_USERNAME }}/${{vars.KAGGLE_REPO}} -p ./
          unzip ${{vars.KAGGLE_REPO}}.zip
          mkdir -p ${{vars.KAGGLE_REPO}}/${DATE_RANGE}

      - name: 5. ğŸª„Generate daily CSV report
        run: |
          ghtrend daily ${{ vars.KAGGLE_REPO }}/${DATE_RANGE}/$(date '+%Y%m%d').csv

      - name: 5. â˜ï¸Upload CSV to Kaggle
        run: kaggle datasets version -p ${{ vars.KAGGLE_REPO }} -m "$(date '+%Y%m%d') daily github trend uploaded."
